### ISSUE TITLE
Extremely slow TCP response/Ack from FTP server while storing file to the server

### ISSUE THREAD

**Issue by Ali-Moajiz** [gezedo/lwftp#11]
’ve been using this FTP library to transfer a 40MB file from a client (Xilinx Zynq 7000-based custom board) to a server. Since I'm working without an RTOS (NO_SYS = 1) in LwIP, I've been directly calling the necessary functions without the tcpip_callback function.

The issue I’m encountering is that during the file transfer, each FTP-DATA packet takes approximately 46ms for the TCP to ACK the packet, which is quite high compared to the expected ACK time for the FTP protocol. When I transfer the same size file between two PCs using a different Python-based library, the ACK time is around 10ms.

Could this be a configuration issue on my end, or is there a potential bug in the library that's causing the delay?

**Comment by Arturron** [comment]
download

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)

**Comment by scaprile** [comment]
There is no such thing as an "expected ACK time for the FTP protocol", TCP is lwIP stuff, and the timing depends on lwIP, your device, your lwIP config, your hardware, your network, your provider, all intermediaries, your other end.

**Comment by aleroldan156** [comment]
I think this will help you.
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)
