### ISSUE TITLE
Re-write the lwftp client library with Socket APIs

### ISSUE THREAD

**Issue by zhaoxin39913** [gezedo/lwftp#6]
Dear Author,

Currenlty we have already integrated the lwftp client library into our old product which is based on lwip stack. However in new product we have  moved to nechiStack as the TCP/IP stack which is not compatible with the lwip raw/callback API that lwftp is currently using.  

Have your team implemented lwftp with standard socket API , or we need re-write it ourself if we want to port the lwftp into socket API based RTOS ?

**Comment by scaprile** [comment]
Perhaps the main author would differ, in my opinion the reason for this library was to provide an FTP client for lwIP's RAW API. There are many socket-based FTP clients to choose from, so I wouldn't bet on this one going that way.

**Comment by zhaoxin39913** [comment]
Thanks for the comments.  Yes, we understand there are many 3rd party open-source socket-based FTP client libraries. Just because our application layer has got tightly coupled with lwftp library, we are seeking if there are exsiting socket-based implementation. 

Anyway, we will change the code ourself to make adaption for socket API, thanks.
